#!/bin/bash
source /home/pi/tflite1/tflite1-env/bin/activate
#tflite1-env is the virtualenv
cd tflite1
sleep 8
python3 /home/pi/tflite1/DetectionCyclisteJSON2.py --modeldir=Sample_TFLite_model --edgetpu

